[package]
name = "example"
version = "0.2.2"
edition = "2021"

[features]
default = []
tv = ["assert_tv/enabled"]

[dependencies]
assert_tv = { path = "../assert_tv" }


[dev-dependencies]
assert_tv = {  path = "../assert_tv"  }
assert_tv_macros = { path = "../assert_tv_macros" }