[package]
name = "assert_tv_macros"
version = "0.4.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
assert_tv = { path = "../assert_tv"}
proc-macro2 = "1.0.93"
