[package]
name = "assert_tv"
version = "0.1.0"
edition = "2021"
authors = ["Amin Faez <faez@utilacy.de>"]

[features]
default = []
enabled = []

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
log = "0.4.25"
anyhow = "1.0.95"
serde_yaml = "0.9.34+deprecated"
