[package]
name = "assert_tv"
version = "0.1.1"
edition = "2021"
authors = ["Amin Faez <faez@utilacy.de>"]

[features]
default = []
enabled = ["serde", "serde_yaml", "serde_json", "log"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }
anyhow = "1.0"
serde_yaml = {  version = "0.9", optional = true }
